-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 22:21:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema serverproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema serverproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `serverproject` ;
USE `serverproject` ;

-- -----------------------------------------------------
-- Table `mydb`.`marktNaam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serverproject`.`marktNaam` (
  `idMarktNaam` INT NOT NULL AUTO_INCREMENT,
  `marktnaamDb` VARCHAR(45) NOT NULL,
  `baseCoin` VARCHAR(45) NOT NULL,
  `marktCurrency` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarktNaam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`handelsplaats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serverproject`.`handelsplaats` (
  `idHandelsplaats` INT NOT NULL AUTO_INCREMENT,
  `handelsplaatsNaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHandelsplaats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marktLijsten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serverproject`.`marktLijsten` (
  `naamHandelsplaats` VARCHAR(45) NOT NULL,
  `minimumTrade` DOUBLE NOT NULL DEFAULT 0,
  `idMarktNaam` INT NOT NULL,
  `idHandelsplaats` INT NOT NULL,
  PRIMARY KEY (`idMarktNaam`, `idHandelsplaats`),
  INDEX `verzinzelf1_idx` (`idHandelsplaats` ASC),
  CONSTRAINT `verzinzelf`
    FOREIGN KEY (`idMarktNaam`)
    REFERENCES `mydb`.`marktNaam` (`idMarktNaam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verzinzelf1`
    FOREIGN KEY (`idHandelsplaats`)
    REFERENCES `mydb`.`handelsplaats` (`idHandelsplaats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marktUpdate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serverproject`.`marktUpdate` (
  `high` DOUBLE NOT NULL,
  `low` DOUBLE NOT NULL,
  `volume` DOUBLE NOT NULL,
  `volumeBTC` DOUBLE NOT NULL,
  `bid` DOUBLE NOT NULL,
  `ask` DOUBLE NOT NULL,
  `last` DOUBLE NOT NULL,
  `idMarktNaam` INT NOT NULL,
  `idHandelsplaats` INT NOT NULL,
  PRIMARY KEY (`idMarktNaam`, `idHandelsplaats`),
  CONSTRAINT `verzinzelf2`
    FOREIGN KEY (`idMarktNaam` , `idHandelsplaats`)
    REFERENCES `mydb`.`marktLijsten` (`idMarktNaam` , `idHandelsplaats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `serverproject` ;

-- -----------------------------------------------------
-- Table `serverproject`.`tdafads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serverproject`.`tdafads` (
  `fasd` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`fasd`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;